default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: 2016-election-development

test:
  <<: *default
  database: 2016-election-test

production:
  <<: *default
  database: ENV['DATABASE_URL']
